### ISSUE TITLE
invalid --tag error during build

### ISSUE THREAD

**Issue by ezeagwulae** [jctaveras/heroku-deploy#18]
I've been trying to get this action to work. Looks like the [`--tag` option](https://github.com/jctaveras/heroku-deploy/blob/3cd578b9e4df8f75412ce38416feff57dec36ae9/index.js#L26) is not picking up the app_name and default web formation. 
![image](https://user-images.githubusercontent.com/29292857/118068473-453bb680-b357-11eb-8afd-3ce79021770e.png)

Although I do have HEROKU_APP_NAME in my repo secrets, the build only works if I entered app_name and formation directly in file

```
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v2.1.3  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: 'web-backend' # you application name
          dockerfile_path: 'src/backend' # set the path to the folder where the Dockerfile is located
          options: '' # Docker Build Options
          formation: 'web' # Docker Dyno Formation. By default is web
```

Any idea?
